# Generated by Django 4.1 on 2022-09-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_status_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='special_offers',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default=0, max_length=100),
            preserve_default=False,
        ),
    ]
