# Generated by Django 4.1 on 2022-09-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_special_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_0',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=200),
        ),
    ]
