# Generated by Django 4.1 on 2022-09-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_price_alter_product_price_0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_0',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
