# Generated by Django 4.1.1 on 2022-09-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_price_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('M', 'M'), ('S', 'S'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default=0, max_length=100),
            preserve_default=False,
        ),
    ]
