# Generated by Django 4.1.1 on 2022-09-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_contact_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=200)),
                ('carousel_image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='item_status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('SECOND HAND', 'SECOND HAND')], default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='agent_image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
